name: Reproduce

on:
  push:
    branches: [ master, gh-actions ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  steamkit2:
    name: SteamKit on ${{ matrix.os }} - ${{ matrix.configuration }}

    strategy:
      matrix:
        os: [ ubuntu-24.04-arm ]
        configuration: [ Debug ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    - name: Build SteamKit
      run: dotnet build --configuration ${{ matrix.configuration }} SteamKit2/SteamKit2/SteamKit2.csproj -bl:SteamKit2.binlog

    - name: Build SteamLanguageParser
      run: dotnet build --configuration ${{ matrix.configuration }} Resources/SteamLanguageParser/SteamLanguageParser.csproj -bl:SteamLanguageParser.binlog

    - name: Build ProtobufGen
      run: dotnet build --configuration ${{ matrix.configuration }} Resources/ProtobufGen/ProtobufGen.sln -bl:ProtobufGen.binlog

    - name: Build ProtobufDumper
      run: dotnet build --configuration ${{ matrix.configuration }} Resources/ProtobufDumper/ProtobufDumper.sln -bl:ProtobufDumper.binlog

    - name: Build Samples
      run: dotnet build --configuration ${{ matrix.configuration }} Samples/Samples.sln -bl:Samples.binlog

    - name: Build NetHookAnalyzer2
      run: dotnet build --configuration ${{ matrix.configuration }} Resources/NetHookAnalyzer2/NetHookAnalyzer2.sln -bl:NetHookAnalyzer2.binlog
      if: matrix.os == 'windows-latest'

    - name: Upload build binary logs
      uses: actions/upload-artifact@v4
      with:
        name: BuildLog
        path: './*.binlog'

    - name: Run Tests
      run: >
        dotnet test 
        --configuration ${{ matrix.configuration }}
        --verbosity normal
        SteamKit2/Tests/Tests.csproj
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=lcov
        /p:CoverletOutput='./Coverage/lcov.info'
        /p:Include="[SteamKit2]SteamKit*"
        /p:Exclude="[SteamKit2]SteamKit2*Internal*"

    - name: Upload test coverage
      uses: codecov/codecov-action@v5
      if: matrix.configuration == 'Debug'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./SteamKit2/Tests/Coverage/lcov.info
        fail_ci_if_error: false
        verbose: true

